---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
data <- read.csv("activity.csv")

#removing NA records
data_no_missing <- na.omit(data)

```

## What is mean total number of steps taken per day?


```{r}
daily_step_counts <- setNames(aggregate(data_no_missing$steps, list(data_no_missing$date), FUN=sum), c("date", "total_steps"))

hist(daily_step_counts$total_steps, xlab="Total number of steps",breaks=20, main="Total number of daily steps")

mean_daily_steps <- mean(daily_step_counts$total_steps)
median_daily_steps <- median(daily_step_counts$total_steps)

sprintf("The mean total number of steps is: %f",mean_daily_steps)
sprintf("The median total number of steps is: %i",median_daily_steps)
```


## What is the average daily activity pattern?

```{r}
average_interval_steps <- setNames(aggregate(data_no_missing$steps, list(data_no_missing$interval), FUN=,mean), c("interval", "mean_steps"))

plot(x=average_interval_steps$interval, y=average_interval_steps$mean_steps, type="l", xlab="5 minute interval", ylab="Average steps", main="Average daily steps across 5 minute intervals")

#Sorting by mean steps decreasing to find the max mean steps
sortedData <- average_interval_steps[order(average_interval_steps$mean_steps, decreasing=TRUE),]

#Selecting top interval as highest average
highest_average <- sortedData[1,1]

sprintf("The highest average interval was: %i",highest_average)
```


## Imputing missing values

```{r}

count_of_missing  <- sum(is.na(data$steps))

sprintf("The number of missing steps is: %i",count_of_missing)



```


## Are there differences in activity patterns between weekdays and weekends?
